project:
  type: website
  output-dir: "."

website:
  title: "Nada Trabelsi"
  navbar:
    pinned: true
    left:
      - text: Project
        href: project.qmd
      - text: Blog
        href: blog-listing.qmd
      - text: Python Basics
        href: basic-python-intro.ipynb
      - text: Python Basics with R
        href: danl-210-quarto-reticulate.qmd
  page-footer: 
    center: "Powered with GitHub and Quarto<br>© Nada Trabelsi, 2024"

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    mainfont: system-ui; 
    highlight-style: atom-one
    css: styles.css
    toc: false
    include-after-body: target_blank.html
    
