# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eAYY7Jo2UgWvr3VvbmO7ZNLLKU8nousZ
"""

title: "Unifying Environmental, Social, and Governance Metrics with Financial Analysis"
author: Nada Trabelsi
date: 5/16/2024

toc: true
toc-title: "Table of Contents"
toc-depth: 2
number-sections: true

fig-width: 9

execute:
  code-tools: true
  message: false
  warning: false

"""# Introduction"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

esg_proj = pd.read_csv("https://bcdanl.github.io/data/esg_proj.csv")