{
  "hash": "b1589f70aea689c2f886ba57b8dcf4f3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Ben and Jerry's Ice Cream\nauthor: Nada Trabelsi\ndate: 2026-02-11\ncategories: [code, data analysis] # tags for a blog post (e.g., python)\nimage: benandjerrys.png \n\nexecute: \n  warning: false\n  message: false\n  \ntoc: true\n---\n# Introduction to the Dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(skimr)\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(stargazer)\nice_cream <- read_csv('https://bcdanl.github.io/data/ben-and-jerry-cleaned.csv')\n```\n:::\n\nThis dataset explores Ben and Jerry's ice cream sales with several variables, including the unit price, flavor, size, and customer information. We will be exploring the top flavors by region and the relationship region, flavors, size, and household size may have with unit price. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nskim(ice_cream)\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |          |\n|:------------------------|:---------|\n|Name                     |ice_cream |\n|Number of rows           |21974     |\n|Number of columns        |17        |\n|_______________________  |          |\n|Column type frequency:   |          |\n|character                |4         |\n|logical                  |8         |\n|numeric                  |5         |\n|________________________ |          |\n|Group variables          |None      |\n\n\n**Variable type: character**\n\n|skim_variable | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:-------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|flavor_descr  |         0|             1|   3|  30|     0|       50|          0|\n|size1_descr   |         0|             1|   9|   9|     0|        2|          0|\n|region        |         0|             1|   4|   7|     0|        4|          0|\n|race          |         0|             1|   5|   5|     0|        4|          0|\n\n\n**Variable type: logical**\n\n|skim_variable   | n_missing| complete_rate| mean|count                 |\n|:---------------|---------:|-------------:|----:|:---------------------|\n|usecoup         |         0|             1| 0.11|FAL: 19629, TRU: 2345 |\n|married         |         0|             1| 0.60|TRU: 13276, FAL: 8698 |\n|hispanic_origin |         0|             1| 0.05|FAL: 20919, TRU: 1055 |\n|microwave       |         0|             1| 0.98|TRU: 21567, FAL: 407  |\n|dishwasher      |         0|             1| 0.77|TRU: 16983, FAL: 4991 |\n|sfh             |         0|             1| 0.73|TRU: 16076, FAL: 5898 |\n|internet        |         0|             1| 0.84|TRU: 18529, FAL: 3445 |\n|tvcable         |        34|             1| 0.64|TRU: 13954, FAL: 7986 |\n\n\n**Variable type: numeric**\n\n|skim_variable    | n_missing| complete_rate|        mean|          sd|      p0|     p25|        p50|         p75|        p100|hist  |\n|:----------------|---------:|-------------:|-----------:|-----------:|-------:|-------:|----------:|-----------:|-----------:|:-----|\n|priceper1        |         0|             1|        3.31|        0.67|       0|       3|       3.34|        3.59|        9.48|▁▇▂▁▁ |\n|household_id     |         0|             1| 16612005.04| 11685954.46| 2000358| 8142253| 8401573.00| 30183891.00| 30440689.00|▂▇▁▁▇ |\n|household_income |         0|             1|   125290.80|    57188.36|   40000|   80000|  110000.00|   170000.00|   310000.00|▇▃▅▂▁ |\n|household_size   |         0|             1|        2.46|        1.34|       1|       2|       2.00|        3.00|        9.00|▇▃▁▁▁ |\n|couponper1       |         0|             1|        0.13|        0.52|       0|       0|       0.00|        0.00|        8.98|▇▁▁▁▁ |\n\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntop3_by_region <- ice_cream |> \n  group_by(region, flavor_descr) |> \n  summarize(n_purchased = n(), .groups = 'drop') |> \n  group_by(region) |> \n  arrange(region, desc(n_purchased)) |> \n  slice_head(n = 3) |> \n  ungroup() \ntop3_by_region <- top3_by_region |> \n    mutate(flavor_descr = factor(flavor_descr, \n                               levels = top3_by_region |> \n                                 group_by(region) |> \n                                 arrange(region, desc(n_purchased)) |> \n                                 pull(flavor_descr) |> \n                                 unique()))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(top3_by_region,\n       aes( x = flavor_descr,\n            y = n_purchased)) +\n  geom_bar(stat = \"identity\",\n           aes(fill = flavor_descr)) +\n  facet_wrap(~region,\n             scales = \"free_x\",\n             nrow = 1) +\n  labs(title = \"Top 3 Flavors by Region\")+\n  xlab(\"Flavor\")+\n  ylab(\"Total Units Purchased\")+\n  theme_bw()+\n  theme(\n    legend.position = 'none',\n    axis.text.x = element_text(angle = 45, hjust = 1)\n  ) +\n  scale_fill_brewer(palette = \"Pastel1\")\n```\n\n::: {.cell-output-display}\n![](ben_jerrys_blog_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n# Regression Model\n\n## Data Prep\n\n::: {.cell}\n\n```{.r .cell-code}\nice_cream <- ice_cream |> \n # filter(flavor_descr %in% c(\"CHERRY GRCA\", \"CHC FUDGE BROWNIE\", \"CHUNKY MONKEY\", \"PHISH FOOD\", \"HEATH COFFEE CRUNCH\", \"CHC CHIP C-DH\")) |> \n  mutate(flavor_descr = factor(flavor_descr),\n         flavor_descr = fct_relevel(flavor_descr, \"CHERRY GRCA\", \"CHC FUDGE BROWNIE\", \"CHUNKY MONKEY\", \"PHISH FOOD\", \"HEATH COFFEE CRUNCH\", \"CHC CHIP C-DH\"))\n```\n:::\n\n\n\n## Splitting into Treaining and Test Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(9)\n\nice_cream<- ice_cream |> \n  mutate(rnd = runif(n()))\n\ndtrain<- ice_cream |> \n  filter(rnd > 0.3)\n\ndtest<- ice_cream |> \n  filter(rnd <= 0.3)\nnrow(dtrain)/ nrow(ice_cream)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7044689\n```\n\n\n:::\n:::\n\n## Training the Model\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(priceper1 ~ region + flavor_descr + usecoup,\n            data = dtrain)\n```\n:::\n\n\n## Regression Table\n\n```{.r .cell-code}\nstargazer(model, type = \"html\")\n```\n\n\n<table style=\"text-align:center\"><tr><td colspan=\"2\" style=\"border-bottom: 1px solid black\"></td></tr><tr><td style=\"text-align:left\"></td><td><em>Dependent variable:</em></td></tr>\n<tr><td></td><td colspan=\"1\" style=\"border-bottom: 1px solid black\"></td></tr>\n<tr><td style=\"text-align:left\"></td><td>priceper1</td></tr>\n<tr><td colspan=\"2\" style=\"border-bottom: 1px solid black\"></td></tr><tr><td style=\"text-align:left\">regionEast</td><td>0.143<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.016)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">regionSouth</td><td>-0.019</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.015)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">regionWest</td><td>0.043<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.015)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrCHC FUDGE BROWNIE</td><td>-0.093<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.028)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrCHUNKY MONKEY</td><td>-0.173<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.030)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrPHISH FOOD</td><td>-0.129<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.031)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrHEATH COFFEE CRUNCH</td><td>-0.150<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.029)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrCHC CHIP C-DH</td><td>0.051<sup>*</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.029)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrAMERICONE DREAM</td><td>-0.112<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.032)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrBANANA SPLIT</td><td>-0.215<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.036)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrBLACK</td><td>TAN</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.171)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrBROWNIE BATTER</td><td>-0.052</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.071)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrBUTTER PECAN</td><td>-0.068</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.054)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrCAKE BATTER</td><td>-0.204<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.043)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrCHC</td><td>0.039</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.084)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrCHC ALMOND NOUGAT</td><td>-0.147<sup>**</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.073)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrCHUBBY HUBBY</td><td>-0.094<sup>**</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.047)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrCINNAMON BUNS</td><td>-0.223<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.036)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrCOFFEE</td><td>0.091</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.101)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrCREME BRULEE</td><td>-0.227<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.041)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrDOUBLE CHC FUDGE SWR</td><td>0.092</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.659)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrDUBLIN MUDSLIDE</td><td>-0.138<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.044)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrFOSSIL FUEL</td><td>-0.193<sup>**</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.085)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrHALF BAKED</td><td>-0.177<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.034)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrHEATH CANDY EVERYTHING BUT THE</td><td>-0.163<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.038)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrHEATH CRUNCH</td><td>-0.032</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.040)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrIMAGINE WHIRLED PEACE</td><td>-0.198<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.036)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrKARAMEL SUTRA</td><td>-0.134<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.033)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrMAGIC BROWNIES</td><td>-0.249<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.062)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrMINT CHC CHUNK</td><td>-0.007</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.068)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrNEAPOLITAN DYNAMITE</td><td>-0.200<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.058)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrNEW YORK SUPER FUDGE CHUNK</td><td>-0.153<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.031)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrOATMEAL COOKIE CHUNK</td><td>-0.151<sup>**</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.061)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrONE CSK BROWNIE</td><td>-0.294<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.037)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrOXFORD MINT CHC COOKIE</td><td>-0.147<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.047)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrPB CUP</td><td>-0.147<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.032)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrPISTACHIO PISTACHIO</td><td>-0.164<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.034)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrPUMPKIN CSK</td><td>-0.405<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.070)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrRSP CHC CHUNK</td><td>0.014</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.093)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrSMORES</td><td>0.036</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.057)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrSTR</td><td>0.218</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.250)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrSTR CSK</td><td>-0.182<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.038)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrSTRAWBERRIES</td><td>CREAM</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.220)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrSWEET CREAM</td><td>COOKIES</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.177)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrTRIPLE CARAMEL CHUNK</td><td>-0.072</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.085)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrTURTLE SOUP</td><td>-0.213<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.058)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrVAN</td><td>0.084<sup>**</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.039)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrVAN CARAMEL FUDGE</td><td>-0.198<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.049)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrVERMONTY PYTHON</td><td>-0.137<sup>**</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.068)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">flavor_descrW-N-C-P-C</td><td>-0.182<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.034)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">usecoup</td><td>0.047<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.017)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">Constant</td><td>3.398<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.020)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td colspan=\"2\" style=\"border-bottom: 1px solid black\"></td></tr><tr><td style=\"text-align:left\">Observations</td><td>15,480</td></tr>\n<tr><td style=\"text-align:left\">R<sup>2</sup></td><td>0.029</td></tr>\n<tr><td style=\"text-align:left\">Adjusted R<sup>2</sup></td><td>0.025</td></tr>\n<tr><td style=\"text-align:left\">Residual Std. Error</td><td>0.659 (df = 15428)</td></tr>\n<tr><td style=\"text-align:left\">F Statistic</td><td>8.882<sup>***</sup> (df = 51; 15428)</td></tr>\n<tr><td colspan=\"2\" style=\"border-bottom: 1px solid black\"></td></tr><tr><td style=\"text-align:left\"><em>Note:</em></td><td style=\"text-align:right\"><sup>*</sup>p<0.1; <sup>**</sup>p<0.05; <sup>***</sup>p<0.01</td></tr>\n</table>\n## Results\n\nRegion appears to affect price as prices increases by 0.143 compared to the Central region. It appears most flavors price are lower than Cherry Garcia, the most popular flavor across all four regions. Indicating a higher price due to popular demand. It also appears using a coupon also increases the price by a small amount, indicating customers may likely be using coupons on higher priced ice-cream. However it is important to note that this model has a very high residual standard error of 0.659 and a low R2 of 0.029. This means only about 3% of the outcome is explained by the model. \n",
    "supporting": [
      "ben_jerrys_blog_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}